from django.urls import path, register_converter
from .views import *
from Accounts.utils import HashIdConverter
register_converter(HashIdConverter, "hashid")

urlpatterns = [
    path('audit/form/', audit_form, name = 'audit_form'),
    path('rate/feedback/', rating, name = 'rating'),
    path('dispatch/list/', dispatch_list , name = 'dispatch_list'),
    path('inspection/form/', inspection_form, name = 'inspection_form'),
    path('case/note/add/<hashid:id>/', case_note_create, name = 'case_note_create'),
    path('stock/request/form/', stock_req_form, name = 'stock_req_form'),
    path('property/form/', property_add, name='property_add'),
    path('property/<hashid:id>/', property_edit, name='property_edit'),
    path('occurrence/form/', occurrence_form, name='occurrence_form'),
    path('occurrence/report/', occurrence_report, name='occurrence_report'),
    path('panic/request/', panic_system, name='panic_system'),
    path('ambulance/request/', AmbulanceRequest.as_view(), name='ambulance_request'),
    path('ambulance/request/report/', AmbulanceRequestReport.as_view(),
         name='ambulance_request_report'),
    path('ambulance/request/detail/<int:pk>/', AmbulanceRequestDetail.as_view(),name='AmbulanceRequestDetail'),
    path('ambulance/track/<hashid:pk>/', AmbulanceTrackLocation.as_view(), name='AmbulanceTrackLocation'),
    path('ambulance/request/update/<int:pk>/', AmbulanceRequestUpdate.as_view(), name='AmbulanceRequestUpdate'),
    path('ambulance/request/delete/<int:pk>/', AmbulanceRequestDelete.as_view(), name='AmbulanceRequestDelete'),

    path('audit/report/', audit_report, name='audit_report'),
    path('inspection/report/', inspaction_report, name='inspaction_report'),
    path('stock/request/report/', stock_req_reports, name='stock_req_reports'),
    path('hospital/transfer/report/', hospital_transfer_report,
         name='hospital_transfer_report'),
    path('hospital/transfer/request/',
         hospital_transfer, name='hospital_transfer'),
    path('hospital/transfer/up/<hashid:pk>/', update_hospital_request, name='update_hospital_request'),
    path('hospital/transfer/details/<hashid:pk>/', details_hospital_request, name='details_hospital_request'),
    path('hospital/transfer/delete/<hashid:pk>/', delete_hospital_request, name='delete_hospital_request'),
     path('panic/requests/', check_panic_requests, name = 'check_panic_requests'),
     path('transfer/task/', task_transfer_req, name = 'task_transfer_req'),
     path('find/route/', get_route, name = 'get_route'),
     path('individual/panic/location/<hashid:id>/', check_panic_requests_location, name = 'check_panic_requests_location'),
     path('delete/panic/request/<hashid:id>/', del_panic, name = 'del_panic'),
     path('property/report/', property_report, name = 'property_report'),
     path('schedule/report/', schedule_report, name = 'schedule_report'),
     path('delete/<hashid:id>/', common_delete, name = 'common_delete'),
     path('edit/occurrence/<hashid:id>/', edit_occurrence, name = 'edit_occurrence'),
     path('notification/panic/', Panic_Noti.as_view()),
     path('feedback/', feedback, name = 'feedback'),
     path('delete/property/<hashid:id>/', property_del, name = 'property_del'),
     path('invoice/<hashid:id>/', invoice_pdf_property, name = 'invoice_pdf_property'),
     path('FAQ/', faq, name = 'faq'),
     path('create/FAQ/', create_faq, name = 'create_faq'),
     path('edit/FAQ/<hashid:id>/', edit_faq, name = 'edit_faq'),
     path('delete/faq/<hashid:id>/', del_faq, name = 'del_faq'),
     path('showing/feedbacks/', feedbacks, name = 'feedbacks'),
     path('deleting/feedback/<hashid:id>/', del_feedback, name = 'del_feedback'),
     path('delete/case/<hashid:id>/', case_del, name = 'case_del'),
     path('case/notes/all/', case_notes, name = 'case_notes'),
]
