from django.contrib import admin
from .models import *
# Register your models here.

admin.site.register(ScheduleModel)
admin.site.register(TaskModel)
admin.site.register(TaskTransferModel)
admin.site.register(StockRequestModel)
admin.site.register(Package)
admin.site.register(PaystubModel)
admin.site.register(InspectionModel)
admin.site.register(MembershipModel)
admin.site.register(MembershipNoti)
admin.site.register(MembershipRenewalNoti)
admin.site.register(Audit)
admin.site.register(Leaves)
admin.site.register(PayrolDeduction)
admin.site.register(Electric_Cash_Receipt)
admin.site.register(Invoice_cash_received_by)
admin.site.register(Electric_Cash_Receipt_Invoice)
admin.site.register(Expense_Reimbursement_Record)
admin.site.register(ExpenseTransactions)
admin.site.register(PhotoGraphicalEvidence)
admin.site.register(ExpenseRequestSummary)
admin.site.register(RequestedBy)
admin.site.register(SupplierOrCompany)
admin.site.register(CourierToThisAddress)
admin.site.register(PurchaseOrder)
admin.site.register(PackagingForVehicle)
admin.site.register(VehicleMaintenance)
admin.site.register(VehicleCallAsign)
admin.site.register(VehicleMaintenanceTotal)
admin.site.register(TermsAndConditions)
admin.site.register(POAPPROVEDBY)
admin.site.register(PurchaseApproval)
admin.site.register(InitialReceiverOfGoods)
admin.site.register(PO_Items_Received)
admin.site.register(PurchaseInspectedBy)
admin.site.register(Quality_Control_Inspection)
admin.site.register(Product)
admin.site.register(Product_totals)
admin.site.register(Services_Training)
admin.site.register(Service_Totals)
admin.site.register(QuotePreparedBy)
admin.site.register(ProspectiveClient)
admin.site.register(ServiceRequest)
admin.site.register(ServiceDetails)
admin.site.register(Code)
admin.site.register(EmergencyOperations)
admin.site.register(TotalCallCosting)
admin.site.register(EventsProspectiveClient)
admin.site.register(EventsServiceDetails)
admin.site.register(EventServiceRequest)
admin.site.register(EventServiceDetailRiskLevel)
admin.site.register(EventParticularServiceDescription)
admin.site.register(EventSportParticulars)
admin.site.register(TotalEventSportCosting)
admin.site.register(EventServiceElement)
admin.site.register(EventServiceInclusionDescription)
admin.site.register(EventServiceInclusion)
admin.site.register(EventServiceExclusionDescription)
admin.site.register(EventServiceExclusion)
admin.site.register(ElectricInvoiceSummary)






