from django.urls import path, register_converter
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from Accounts.utils import HashIdConverter
register_converter(HashIdConverter, "hashid")

urlpatterns = [
    path('add/member/', add_member, name='add_member'),
    path('add/package/', add_package, name='add_package'),
    path('packages/', packages, name='packages'),
    path('get/membership/', getmembership, name='getmembership'),
    path('members/', members, name='members'),
    path('schedule/trip/', ScheduleTrip.as_view(), name='shcedule_trip'),
    path('scheduled/trips/', TripSchedules.as_view(), name='trip_schedules'),
    path('scheduled/detail/<hashid:pk>/', ScheduleDetails, name='schedule_details'),
    path('scheduled/update/<hashid:pk>/', UpdateSchedule.as_view(), name='schedule_update'),
    path('scheduled/delete/<hashid:pk>/', DeleteSchedule.as_view(), name='schedule_delete'),
    path('scheduled/complete/<hashid:pk>/', schedule_status_change, name='schedule_status_change'),
    path('track/schedule/<hashid:pk>/',
         TrackSchedule.as_view(), name='track_schedule'),

    path('complete/schedule/', CompletedSchedule.as_view(), name='complete_schedule'),
    path('accepted/schedule/', AcceptedSchedule.as_view(), name='accepted_schedule'),

    path('add/paystub/', add_paystub, name='add_paystub'),
    path('paystub/report', paystub_report, name='paystub_report'),
    path('paystub/update/<hashid:pk>/', update_paystub_report, name='update_paystub_report'),
    path('paystub/delete/<hashid:pk>/', delete_paystub, name='delete_paystub'),
    path('create/task/', task_create, name='task_create'),
    path('task/report/', TasksList.as_view(), name='task_list'),
    path('task/update/<hashid:pk>/', UpdateTask.as_view(), name='update_task'),
    path('task/delete/<hashid:pk>/', DeleteTask.as_view(), name='delete_task'),
    path('task/detail/<hashid:pk>/', task_detail, name='task_detail'),
    path('transfer/task/<hashid:pk>/', TransferTask.as_view(), name='transfer_task'),
    path('transferred/tasks/', TransferredTasks.as_view(), name='transferred_task'),
    path('request/stock/', stock_request, name='stock_request'),
    path('cancel/stock/request/', cancel_stock_request,
         name='cancel_stock_request'),
    path('stock/requests/', StockRequest.as_view(), name='stock_requests'),
    path('stock/request/delete/<hashid:pk>/',
         DeleteStock.as_view(), name='DeleteStock'),
    path('stock/request/detail/<hashid:pk>/', StockRequestDetail.as_view(), name='stock_detail'),
    path('add/package/', add_package, name='add_package'),
    path('edit/package/<hashid:id>/', edit_package, name='edit_package'),
    path('delete/package/<hashid:id>/', del_package, name='del_package'),
    path('create/inspection/', create_inspection, name = 'create_inspection'),
    path('inspection/reports/', inpection_reports, name = 'inpection_reports'),
    path('delete/inspection/<hashid:id>/', del_inspection, name = 'del_inspection'),
    path('update/inspection/<hashid:id>/', edit_inspection, name = 'edit_inspection'),


    path('payment/<hashid:id>/', payment, name = 'payment'),
    path('payment/backend/', payment_backend, name = 'payment_backend'),
    path('purchased/', package_purchased, name = 'package_purchased'),
    path('membership/notificattions/', membership_noti, name = 'membership_noti'),
    path('membership/details/individual/<int:id>/', viewing_membership_details_individual, name = 'viewing_membership_details_individual'),
    path('mark/as/read/membership/notification/<int:id>/', membership_noti_mark_as_seen, name = 'membership_noti_mark_as_seen'),
    path('renewal/membership/', user_membership_renewal_noti, name = 'user_membership_renewal_noti'),
    path('mark/as/seen/membership/renewal/notification/<int:id>/', mark_as_seen_membership_renewal_noti, name = 'mark_as_seen_membership_renewal_noti'),
    path('employee/leave/request/', employee_leave, name = 'employee_leave'),
    path('my/leaves/<hashid:id>/', my_leaves, name = 'my_leaves'),
    path('employee/leave/reports/', employee_leaves, name = 'employee_leaves'),
    path('delete/leave/report/<hashid:id>/', delete_leaves, name = 'delete_leaves'),
    path('reports/payroll/deductions/', payrol_deduction_reports, name = 'payrol_deduction_reports'),
    path('payroll/deductions/', payroll_deduction_form, name = 'payroll_deduction_form'),
    path('payroll/deduction/individual/report/view/<hashid:id>/', payroll_deduction_individual_report, name = 'payroll_deduction_individual_report'),
    path('delete/payrolldeductionreport/<hashid:id>/', payroll_deduction_delete, name = 'payroll_deduction_delete'),
    path('has_membership_or_not/', has_membership_or_not, name = 'has_membership_or_not'),
    path('change/ScheduleStatus/<int:id>/', changeScheduleStatus, name = 'changeScheduleStatus'),
    path('set/amount/schedule/<int:id>/', setAmountforScheduleTrip, name = 'setAmountforScheduleTrip'),
    path('electronic/cash/', electronic_cash_receipt, name = 'electronic_cash_receipt'),
    path('electronic/invoice/details/<int:id>/', electronic_invoice_details, name = 'electronic_invoice_details'),
    path('financial/reports/', reports, name = 'reports'),
    path('expense/Reimbursement/record/form/', expense_reimbursement_record_form, name = 'expense_reimbursement_record_form'),
    path('expense/transactions/<int:id>/', expense_transactions, name = 'expense_transactions'),
    path('photographical/evidence/<int:expense_reimbursement_record_id>/', photographical_evidence, name = 'photographical_evidence'),
    path('request/summary/<int:expense_reimbursement_record_id>/', request_summary, name = 'request_summary'),
    path('adding/another/expense/<int:expense_reimbursement_record_id>', add_another_transaction, name = 'add_another_transaction'),
    path('order/customer/information/', purchase_order_customer_information, name = 'purchase_order_customer_information'),
    path('vehicle/maintenance/<int:id>/', vehicle_maintenance, name = 'vehicle_maintenance'),
    path('add/more/vehicle/items/<int:id>/', add_another_vehicle_maintenance, name = 'add_another_vehicle_maintenance'),
    path('vehicle/maintainance/totals/<int:id>/', vehicle_maintenance_totals, name = 'vehicle_maintenance_totals'),
    path('order/terms/and/conditions/<int:id>/', terms_and_conditions, name = 'terms_and_conditions'),
    path('purchase/approval/<int:id>/', purchase_approval, name = 'purchase_approval'),
    path('po_items_received_verification/<int:id>/', po_items_received_verification, name = 'po_items_received_verification'),
    path('quality/control/inspection/<int:id>/', quality_assurance_check, name = 'quality_assurance_check'),
    path('email/submission/<int:id>/', email_submission, name = 'email_submission'),
    path('product/details/<int:id>/', product_details, name = 'product_details'),
    path('add/another/product/<int:id>/', add_another_product, name = 'add_another_product'),
    path('product/totals/<int:id>/', product_totals, name = 'product_totals'),
    path('service_training/<int:id>/', services_training, name = 'services_training'),
    path('add/another/service/<int:id>/', add_another_service, name = 'add_another_service'),
    path('services/total/<int:id>/', service_totals, name = 'service_totals'),
    path('reviewing/submission/<int:id>/', review_submission_for_order, name = 'review_submission_for_order'),
    path('details/of/prospective/clint/', details_of_prospective_client, name = 'details_of_prospective_client'),
    path('service/details/quotation/<int:id>/', quotation_service_details, name = 'quotation_service_details'),
    path('emergency/operation/<int:id>/', emergency_operations, name = 'emergency_operations'),
    path('add/another/emergency/<int:id>/', add_another_emergency_operation, name = 'add_another_emergency_operation'),
    path('total/call/costing/<int:id>/', total_call_costing, name = 'total_call_costing'),
    path('submission/emergency/operation/<int:id>/', emergency_email_submission, name = 'emergency_email_submission'),
    path('review/submission/for/emergency/operation/<int:id>/', review_submission_for_emergency_operation, name = 'review_submission_for_emergency_operation'),
    path('events/details/of/prospective/client/', details_of_prospective_client_for_events, name = 'details_of_prospective_client_for_events'),
    path('events/service/detail/<int:id>/', event_service_details, name = 'event_service_details'),
    path('event/particular/<int:id>/', event_sport_particulars, name = 'event_sport_particulars'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)